---
service_name: order-service
grpc_hostname: ordersvc
grpc_port: 50052
hz_mode: embedded
hz_client_config: hazelcast-client.local.yaml
---
service_name: catalog-service
grpc_hostname: catalogsvc
grpc_port: 50054
---
service_name: inventory-service
grpc_hostname: invsvc
grpc_port: 50053
---
service_name: account-service
grpc_hostname: acctsvc
grpc_port: 50051
