---
service_name: order-service
hostname: ordersvc
port: 50052
---
service_name: catalog-service
hostname: catalogsvc
port: 50054
---
service_name: inventory-service
hostname: invsvc
port: 50053
---
service_name: account-service
hostname: acctsvc
port: 50051