---
# =========================================================
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: account-service
  name: account-service
  namespace: default
spec:
  replicas: 1
  serviceName: account-service
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - image: "$(REGISTRY)/$(NAMESPACE)/account.service:latest"
          imagePullPolicy: $(IPP)
          livenessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
          name: container-account-svc
          readinessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
            initialDelaySeconds: 30
---
# =========================================================
---
apiVersion: v1
kind: Service
metadata:
  name: acctsvc
spec:
#  clusterIP: None
  selector:
    app: account-service
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
