---
# =========================================================
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: inventory-service
  name: inventory-service
  namespace: default
spec:
  replicas: 1
  serviceName: inventory-service
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - image: "$(REGISTRY)/$(NAMESPACE)/inventory.service:latest"
          imagePullPolicy: $(IPP)
          livenessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5721
          name: container-account-svc
          readinessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5721
            initialDelaySeconds: 30
---
# =========================================================
---
apiVersion: v1
kind: Service
metadata:
  name: invsvc
spec:
#  clusterIP: None
  selector:
    app: inventory-service
  ports:
  - protocol: TCP
    port: 50053
    targetPort: 50053
---
