---
# Service DNS will be "mancenter-service.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: management-center-service
spec:
  selector:
    app: management-center
  ports:
    - name: management-center
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# Only need 1 management center
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-center
spec:
  selector:
    matchLabels:
      app: management-center
  template:
    metadata:
      labels:
        app: management-center
    spec:
      containers:
        - env:
          image: "$(REGISTRY)/$(NAMESPACE)/management-center:latest"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          name: container-hz-management-center
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
---

