---
# =========================================================
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: default
spec:
  replicas: 1
  serviceName: order-service
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - image: "$(REGISTRY)/$(NAMESPACE)/order.service:latest"
          imagePullPolicy: $(IPP)
          livenessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5711
          name: container-account-svc
          readinessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5711
            initialDelaySeconds: 30
---
# =========================================================
---
apiVersion: v1
kind: Service
metadata:
  name: ordersvc
spec:
#  clusterIP: None
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052
---
