---
service_name: account-service
grpc_hostname: acctsvc
grpc_port: 50051
#hazelcast_hostname: acctsvc
#hazelcast_port: 5701
#hazelcast_cluster_name: account
---
service_name: order-service
grpc_hostname: ordersvc
grpc_port: 50052
#hazelcast_hostname: ordersvc
#hazelcast_port: 5711
#hazelcast_cluster_name: order
---
service_name: inventory-service
grpc_hostname: invsvc
grpc_port: 50053
#hazelcast_hostname: invsvc
#hazelcast_port: 5721
#hazelcast_cluster_name: inventory