# Testclient
---
service_name: account-service
grpc_hostname: acctsvc
grpc_port: 50051
---
service_name: order-service
grpc_hostname: ordersvc
grpc_port: 50052
---
service_name: inventory-service
grpc_hostname: invsvc
grpc_port: 50053