---
service_name: account-service
grpc_hostname: localhost
grpc_port: 50051
hz_mode: embedded
# Will add additional fields as needed for cloud deployments
#  apis:
#    - api: open
#      request-map: AccountService.OPEN.Request
#      response-map: AccountService.OPEN.Response
#    - api: adjust
#      request-map: AccountService.ADJUST.Request
#      response-map: AccountService.ADJUST.Response